package codingtest.week7;

 <!-- 상품 별 오프라인 매출 구하기 (sql) -->

    SELECT PRODUCT_CODE, SUM(PRICE * SALES_AMOUNT) AS SALES
    FROM PRODUCT AS S1 JOIN OFFLINE_SALE AS S2
    ON S1.PRODUCT_ID=S2.PRODUCT_ID
    GROUP BY PRODUCT_CODE
    ORDER BY SALES DESC, PRODUCT_CODE ASC;

